name: Flat
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '10 */4 * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12 #install the python needed
      - name: execute py script
        env:
          MS_TOKEN: ${{ secrets.MS_TOKEN }}
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          python3.12 -m venv venv
          source venv/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          pip install playwright==1.40.0
          pip install -r requirements.txt
          python -m playwright install
          # playwright install-deps
          python postprocessing.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Latest TikTok RSS"
          git push
